In [1]:
import statistics
import numpy as np

data = [15, 21, 29, 21, 15, 24, 32, 21, 15, 30]

print("\nOutput:")
mean_value = statistics.mean(data)
print(f"Mean: {mean_value}")

median_value = statistics.median(data)
print(f"Median: {median_value}")

try:
    mode_value = statistics.mode(data)
    print(f"Mode: {mode_value}")
except statistics.StatisticsError as e:
    print(f"Mode: {e}")

variance_value = statistics.variance(data)
print(f"Variance: {variance_value}")

std_dev_value = statistics.stdev(data)
print(f"Standard Deviation: {std_dev_value}")



Output:
Mean: 22.3
Median: 21.0
Mode: 15
Variance: 40.67777777777778
Standard Deviation: 6.377913277693401


In [2]:
name = "Sathish"
age = 20
height = 5.6
is_student = True

print("\nOutput:")
print(f"{name} is {age} years old, {height} feet tall, and is a Engineering student: {is_student}.")



Output:
Sathish is 20 years old, 5.6 feet tall, and is a Engineering student: True.


In [3]:
while True:
    num = int(input("Enter an integer: "))

    if num == 1000:  # Exit condition
        print("Exiting the program.")
        break
    elif num > 0:
        print("The number is positive.\n")
    elif num < 0:
        print("The number is negative.\n")
    else:
        print("The number is zero.\n")


Enter an integer:  5


The number is positive.



Enter an integer:  1001


The number is positive.



Enter an integer:  1000


Exiting the program.


In [4]:
num = int(input("Enter a number: "))

print("Multiplication Table for", num, ":")
for i in range(1, 11):
    print(num, "x", i, "=", num * i)


Enter a number:  5


Multiplication Table for 5 :
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [5]:
fruits = ["Apple", "Banana", "Cherry", "Mango", "Orange"]

print("\nOutput:")
print("Original List of Fruits:", fruits)

fruits.append("Grapes")
print("After Adding Grapes:", fruits)

fruits.remove("Banana")
print("After Removing Banana:", fruits)

fruits.sort()
print("Sorted List:", fruits)

print("Total Number of Fruits:", len(fruits))

print("Fruit at Index 2:", fruits[2])

fruits.reverse()
print("Reversed List:", fruits)



Output:
Original List of Fruits: ['Apple', 'Banana', 'Cherry', 'Mango', 'Orange']
After Adding Grapes: ['Apple', 'Banana', 'Cherry', 'Mango', 'Orange', 'Grapes']
After Removing Banana: ['Apple', 'Cherry', 'Mango', 'Orange', 'Grapes']
Sorted List: ['Apple', 'Cherry', 'Grapes', 'Mango', 'Orange']
Total Number of Fruits: 5
Fruit at Index 2: Grapes
Reversed List: ['Orange', 'Mango', 'Grapes', 'Cherry', 'Apple']


In [6]:
numbers = (10, 25, 30, 45, 60)

print("Original Tuple:", numbers)
print("First Element:", numbers[0])
print("Last Element:", numbers[-1])
print("First Three Elements:", numbers[:3])
print("Last Two Elements:", numbers[-2:])
print("Length of Tuple:", len(numbers))
print("Maximum Value:", max(numbers))
print("Sum of Elements:", sum(numbers))

print("Index of 45:", numbers.index(45))
print("Count of 25 in Tuple:", numbers.count(25))
print("Iterating through the tuple:")
for num in numbers:
    print(num)


Original Tuple: (10, 25, 30, 45, 60)
First Element: 10
Last Element: 60
First Three Elements: (10, 25, 30)
Last Two Elements: (45, 60)
Length of Tuple: 5
Maximum Value: 60
Sum of Elements: 170
Index of 45: 3
Count of 25 in Tuple: 1
Iterating through the tuple:
10
25
30
45
60


In [7]:
student_marks = {
    "Sathish": 90,
    "Krishna": 95,
    "Radha": 92
}

print("\nOutput:")
print("Original Dictionary:", student_marks)
print("Marks of Sathish:", student_marks["Sathish"])

student_marks["Sita"] = 88
print("After Adding Sita:", student_marks)

student_marks["Radha"] = 97
print("After Updating Radha's Marks:", student_marks)

del student_marks["Sathish"]
print("After Removing Sathish:", student_marks)

print("Is Sathish in the dictionary?", "Sathish" in student_marks)

print("Student Names:", list(student_marks.keys()))
print("Marks:", list(student_marks.values()))
print("Student Marks (Key-Value Pairs):", list(student_marks.items()))

print("Iterating through Dictionary:")
for student, marks in student_marks.items():
    print(f"{student}: {marks}")



Output:
Original Dictionary: {'Sathish': 90, 'Krishna': 95, 'Radha': 92}
Marks of Sathish: 90
After Adding Sita: {'Sathish': 90, 'Krishna': 95, 'Radha': 92, 'Sita': 88}
After Updating Radha's Marks: {'Sathish': 90, 'Krishna': 95, 'Radha': 97, 'Sita': 88}
After Removing Sathish: {'Krishna': 95, 'Radha': 97, 'Sita': 88}
Is Sathish in the dictionary? False
Student Names: ['Krishna', 'Radha', 'Sita']
Marks: [95, 97, 88]
Student Marks (Key-Value Pairs): [('Krishna', 95), ('Radha', 97), ('Sita', 88)]
Iterating through Dictionary:
Krishna: 95
Radha: 97
Sita: 88


In [8]:
set1 = {21, 54, 77, 56, 33}
set2 = {21, 43, 54, 66, 43}

print("\nOutput:")
print("Set 1:", set1)
print("Set 2:", set2)

union_set = set1.union(set2)
print("Union:", union_set)

intersection_set = set1.intersection(set2)
print("Intersection:", intersection_set)

difference_set = set1.difference(set2)
print("Difference (Set1 - Set2):", difference_set)

symmetric_difference_set = set1.symmetric_difference(set2)
print("Symmetric Difference:", symmetric_difference_set)

is_subset = set1.issubset(set2)
print("Is Set1 a subset of Set2?", is_subset)

is_superset = set1.issuperset(set2)
print("Is Set1 a superset of Set2?", is_superset)

set1.add(10)
print("Set1 after adding 10:", set1)

set2.discard(8)
print("Set2 after discarding 8:", set2)

are_disjoint = set1.isdisjoint(set2)
print("Are Set1 and Set2 disjoint?", are_disjoint)



Output:
Set 1: {33, 21, 54, 56, 77}
Set 2: {66, 43, 21, 54}
Union: {33, 66, 43, 77, 21, 54, 56}
Intersection: {21, 54}
Difference (Set1 - Set2): {56, 33, 77}
Symmetric Difference: {33, 66, 43, 77, 56}
Is Set1 a subset of Set2? False
Is Set1 a superset of Set2? False
Set1 after adding 10: {33, 21, 54, 56, 10, 77}
Set2 after discarding 8: {66, 43, 21, 54}
Are Set1 and Set2 disjoint? False


In [9]:
def find_largest(numbers):
    if not numbers:
        return None
    largest = numbers[0]
    for num in numbers:
        if num > largest:
            largest = num
    return largest

sample_list = [10, 25, 50, 5, 100, 75]

largest_number = find_largest(sample_list)
print("\nOutput:")
print("The largest number in the list is:", largest_number)



Output:
The largest number in the list is: 100


In [10]:
squares_of_evens = [x**2 for x in range(1, 21) if x % 2 == 0]
print("\nOutput:")
print("Squares of even numbers between 1 and 20:", squares_of_evens)



Output:
Squares of even numbers between 1 and 20: [4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [1]:
product = lambda x, y: x * y

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("Product of", num1, "and", num2, "is:", product(num1, num2))


Enter first number:  2
Enter second number:  4


Product of 2.0 and 4.0 is: 8.0


In [2]:
import numpy as np

one_d_array = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", one_d_array)
print("Shape:", one_d_array.shape)
print("Dimensions:", one_d_array.ndim)
print()

two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", two_d_array)
print("Shape:", two_d_array.shape)
print("Dimensions:", two_d_array.ndim)
print()

three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", three_d_array)
print("Shape:", three_d_array.shape)
print("Dimensions:", three_d_array.ndim)


1D Array:
 [1 2 3 4 5]
Shape: (5,)
Dimensions: 1

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


In [3]:
import numpy as np

np.random.seed(42)
array_5x5 = np.random.randint(1, 101, (5, 5))

print("5x5 Random Integer Array:\n", array_5x5)

element_2_3 = array_5x5[1, 2]
print("\nElement at (2,3):", element_2_3)

row_3 = array_5x5[2, :]
print("\n3rd Row:", row_3)

column_4 = array_5x5[:, 3]
print("\n4th Column:", column_4)

sub_matrix = array_5x5[:3, :3]
print("\nTop-left 3x3 Sub-Matrix:\n", sub_matrix)


5x5 Random Integer Array:
 [[ 52  93  15  72  61]
 [ 21  83  87  75  75]
 [ 88 100  24   3  22]
 [ 53   2  88  30  38]
 [  2  64  60  21  33]]

Element at (2,3): 87

3rd Row: [ 88 100  24   3  22]

4th Column: [72 75  3 30 21]

Top-left 3x3 Sub-Matrix:
 [[ 52  93  15]
 [ 21  83  87]
 [ 88 100  24]]


In [4]:
import numpy as np

array_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 Array:\n", array_4x4)

first_two_rows = array_4x4[:2, :]
print("\nFirst Two Rows:\n", first_two_rows)

last_two_columns = array_4x4[:, -2:]
print("\nLast Two Columns:\n", last_two_columns)

central_sub_matrix = array_4x4[1:3, 1:3]
print("\nCentral 2x2 Sub-Matrix:\n", central_sub_matrix)

second_row = array_4x4[1, :]
print("\nSecond Row:\n", second_row)

third_column = array_4x4[:, 2]
print("\nThird Column:\n", third_column)


Original 4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First Two Rows:
 [[1 2 3 4]
 [5 6 7 8]]

Last Two Columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Central 2x2 Sub-Matrix:
 [[ 6  7]
 [10 11]]

Second Row:
 [5 6 7 8]

Third Column:
 [ 3  7 11 15]


In [5]:
import numpy as np

print()
print("Output:")
array_2d = np.arange(1, 13).reshape(6, 2)
print("Original 2D Array (6x2):\n", array_2d)

array_3d = array_2d.reshape(2, 3, 2)
print("\nReshaped 3D Array (2x3x2):\n", array_3d)

flattened_array = array_3d.flatten()
print("\nFlattened Array:\n", flattened_array)



Output:
Original 2D Array (6x2):
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Reshaped 3D Array (2x3x2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
import numpy as np

array_3x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

print()
print("Output:")
print("Original 3x3 Array:\n", array_3x3)

array_1d = np.array([10, 20, 30])
print("\n1D Array (Shape 1,3):\n", array_1d)

result = array_3x3 + array_1d
print("\nResult after Broadcasting Addition:\n", result)



Output:
Original 3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Array (Shape 1,3):
 [10 20 30]

Result after Broadcasting Addition:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [7]:
import numpy as np

A = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

addition = A + B
subtraction = A - B
multiplication = A * B
division = A / B

print()
print("Output:")
print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)



Output:
Array A:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Array B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element-wise Addition:
 [[11 22 33]
 [44 55 66]
 [77 88 99]]

Element-wise Subtraction:
 [[ 9 18 27]
 [36 45 54]
 [63 72 81]]

Element-wise Multiplication:
 [[ 10  40  90]
 [160 250 360]
 [490 640 810]]

Element-wise Division:
 [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [8]:
import pandas as pd

data = {
    'Name': ['Sathish', 'Krishna', 'Gow'], 
    'Math': [85, 78, 92], 
    'Science': [88, 74, 95], 
    'English': [90, 80, 89] 
}

df = pd.DataFrame(data)

df['Total'] = df[['Math', 'Science', 'English']].sum(axis=1)

def assign_grade(total):
    if total >= 270:
        return 'A' 
    elif total >= 240:
        return 'B' 
    elif total >= 210:
        return 'C'
    else:
        return 'D'

df['Grade'] = df['Total'].apply(assign_grade)
print(df)

      Name  Math  Science  English  Total Grade
0  Sathish    85       88       90    263     B
1  Krishna    78       74       80    232     C
2      Gow    92       95       89    276     A
